name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main   # make sure this matches your repo

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular project
        run: ng build --configuration production --base-href /AngularLab9/

      # 🔥 IMPORTANT: replace YOUR_PROJECT_NAME below
      - name: Copy index.html to 404.html
        run: cp dist/angular-lab9/index.html dist/angular-lab9/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/angular-lab9
